#!/usr/bin/env node
// Generates a Docker Compose (also valid for `docker stack deploy` on a Swarm
// spanning many machines) + Caddyfile for a sharded, zoned cluster.
//
//   node scripts/gen-cluster.mjs --shards 64 --zones 4x4 --gw-per-zone 3 \
//        --world 128x128 --out deploy/generated
//
// Layout produced:
//   shard0..shardN-1     simulation (shard0 also coordinator + control plane)
//   gw-lobby             serves the web client, hands players to their zone
//   gw-z0..gw-zK         one gateway pool per zone (deploy.replicas each)
//   caddy                HTTPS, routes /z/<n>/* to pool n and the rest to lobby
//   postgres, meta0..M-1 accounts, items, trading, friends, messages (--meta M)
//
// See docs/scale-100k.md for sizing.

import fs from 'node:fs';
import path from 'node:path';

function arg(name, def) {
  const i = process.argv.indexOf('--' + name);
  return i >= 0 ? process.argv[i + 1] : def;
}

const shards = Number(arg('shards', 16));
const [zc, zr] = String(arg('zones', '2x2')).split('x').map(Number);
const perZone = Number(arg('gw-per-zone', 2));
const lobby = Number(arg('lobby', 2));
const [cx, cy] = String(arg('world', '64x64')).split('x').map(Number);
const out = arg('out', 'deploy/generated');
const metas = Number(arg('meta', 2));
const zones = zc * zr;

const topology = JSON.stringify({
  world: { chunksX: cx, chunksY: cy },
  shards: Array.from({ length: shards }, (_, i) => `ws://shard${i}:9100`),
});
const zonesJson = JSON.stringify({ cols: zc, rows: zr, urls: Array.from({ length: zones }, (_, z) => `/z/${z}/ws`) });

const y = [];
y.push('# Generated by scripts/gen-cluster.mjs - edit the generator, not this file.');
y.push(`# ${shards} shards, ${zc}x${zr} zones x ${perZone} gateways, lobby x ${lobby}, world ${cx}x${cy} chunks.`);
y.push('#   DOMAIN=... CLUSTER_SECRET=... TOKEN_SECRET=... WORLD_ID=... POSTGRES_PASSWORD=... ADMIN_TOKEN=... docker compose up -d');
y.push('#   (multi-machine: docker swarm init/join, then docker stack deploy -c docker-compose.yml soup)');
y.push('');
y.push('x-common: &common');
y.push('  image: ${IMAGE:-evo-multiplayer}');
y.push('  restart: unless-stopped');
y.push('  networks: [internal]');
y.push('  environment: &env');
y.push(`    TOPOLOGY: '${topology}'`);
y.push(`    ZONES: '${zonesJson}'`);
y.push('    CLUSTER_SECRET: ${CLUSTER_SECRET:?set CLUSTER_SECRET}');
y.push('    TOKEN_SECRET: ${TOKEN_SECRET:?set TOKEN_SECRET}');
y.push('    WORLD_ID: ${WORLD_ID:?set WORLD_ID}');
y.push(`    META_URLS: '${JSON.stringify(Array.from({ length: metas }, (_, i) => `ws://meta${i}:9300`))}'`);
y.push('    ADMIN_TOKEN: ${ADMIN_TOKEN:-}');
y.push('    GAME: ${GAME:-soup}');
y.push("    QUIET: 'true'");
y.push('');
y.push('services:');
for (let i = 0; i < shards; i++) {
  y.push(`  shard${i}:`);
  y.push('    <<: *common');
  y.push("    command: ['node', 'src/server/shard-node.js']");
  y.push(`    environment: { <<: *env, SHARD_ID: '${i}', HOST: '0.0.0.0', PORT: '9100', DATA_DIR: /data }`);
  y.push(`    volumes: ['shard${i}_data:/data']`);
  y.push('    stop_grace_period: 20s');
}
if (metas > 0) {
  y.push('  postgres:');
  y.push('    image: postgres:16-alpine');
  y.push('    restart: unless-stopped');
  y.push('    environment: { POSTGRES_USER: evo, POSTGRES_DB: evo, POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?set POSTGRES_PASSWORD}" }');
  y.push("    volumes: ['pg_data:/var/lib/postgresql/data']");
  y.push('    networks: [internal]');
  for (let i = 0; i < metas; i++) {
    y.push(`  meta${i}:`);
    y.push('    <<: *common');
    y.push("    command: ['node', '--no-warnings', 'src/meta/meta-node.js']");
    y.push(`    environment: { <<: *env, META_ID: '${i}', HOST: '0.0.0.0', PORT: '9300', DATABASE_URL: 'postgres://evo:\${POSTGRES_PASSWORD}@postgres/evo' }`);
    y.push('    depends_on: [postgres]');
  }
}
const gw = (name, zone, replicas) => {
  y.push(`  ${name}:`);
  y.push('    <<: *common');
  y.push("    command: ['node', 'src/server/gateway-node.js']");
  y.push(`    environment: { <<: *env, ZONE: '${zone}', PORT: '8080', HOST: '0.0.0.0', TRUST_PROXY: 'true', MAX_PER_IP: '16' }`);
  y.push(`    deploy: { replicas: ${replicas} }`);
  y.push('    depends_on: [shard0]');
};
gw('gw-lobby', -1, lobby);
for (let z = 0; z < zones; z++) gw(`gw-z${z}`, z, perZone);
y.push('  caddy:');
y.push('    image: caddy:2');
y.push('    restart: unless-stopped');
y.push("    ports: ['80:80', '443:443', '443:443/udp']");
y.push('    environment: { DOMAIN: "${DOMAIN:-localhost}" }');
y.push("    volumes: ['./Caddyfile:/etc/caddy/Caddyfile:ro', 'caddy_data:/data']");
y.push('    networks: [internal]');
y.push('');
y.push('networks:');
y.push('  internal: {}');
y.push('');
y.push('volumes:');
y.push('  caddy_data: {}');
if (metas > 0) y.push('  pg_data: {}');
for (let i = 0; i < shards; i++) y.push(`  shard${i}_data: {}`);

const c = [];
c.push('# Generated by scripts/gen-cluster.mjs.');
c.push('# /z/<n>/* -> zone n gateway pool (prefix stripped, so gateways see /ws);');
c.push('# everything else (web client, /admin, lobby /ws) -> lobby pool.');
c.push('{$DOMAIN} {');
for (let z = 0; z < zones; z++) {
  c.push(`\thandle_path /z/${z}/* {`);
  c.push('\t\treverse_proxy {');
  c.push(`\t\t\tdynamic a {\n\t\t\t\tname gw-z${z}\n\t\t\t\tport 8080\n\t\t\t\trefresh 5s\n\t\t\t}`);
  c.push('\t\t\tlb_policy least_conn');
  c.push('\t\t}');
  c.push('\t}');
}
c.push('\thandle {');
c.push('\t\treverse_proxy {');
c.push('\t\t\tdynamic a {\n\t\t\t\tname gw-lobby\n\t\t\t\tport 8080\n\t\t\t\trefresh 5s\n\t\t\t}');
c.push('\t\t\tlb_policy least_conn');
c.push('\t\t}');
c.push('\t}');
c.push('}');

fs.mkdirSync(out, { recursive: true });
fs.writeFileSync(path.join(out, 'docker-compose.yml'), y.join('\n') + '\n');
fs.writeFileSync(path.join(out, 'Caddyfile'), c.join('\n') + '\n');
console.log(`wrote ${path.join(out, 'docker-compose.yml')} and Caddyfile: ${shards} shards, ${zones} zones x ${perZone}, lobby x ${lobby}, ${metas} meta + postgres`);
