// Durable storage for everything that has value or must persist: accounts,
// sessions, the currency ledger, items, market, trades, friends, messages,
// reports, audit. Unlike the simulation (which may lose the last seconds on
// a crash), everything here is transactional.
//
// Two backends, one SQL dialect:
//   postgres://user:pass@host/db   production (many meta replicas, one DB)
//   sqlite:/path/file.db           single machine / development (node:sqlite)
//   sqlite::memory:                tests
// Queries are written with $1..$n placeholders; for SQLite they become ?1..?n.

import fs from 'node:fs';
import path from 'node:path';

const RETRYABLE_PG = new Set(['40001', '40P01']); // serialization failure, deadlock

export async function openStore(url) {
  if (!url) throw new Error('no DATABASE_URL');
  if (url.startsWith('postgres://') || url.startsWith('postgresql://')) return openPg(url);
  if (url.startsWith('sqlite:')) return openSqlite(url.slice('sqlite:'.length));
  throw new Error(`unsupported DATABASE_URL ${url}`);
}

async function openPg(url) {
  const { default: pg } = await import('pg');
  // BIGINT columns come back as strings by default; our values fit in 2^53.
  pg.types.setTypeParser(20, (v) => Number(v));
  const pool = new pg.Pool({ connectionString: url, max: Number(process.env.DB_POOL || 10) });
  const run = async (client, sql, params = []) => {
    const r = await client.query(sql, params);
    return { rows: r.rows, count: r.rowCount };
  };
  const store = {
    kind: 'pg',
    forUpdate: ' FOR UPDATE',
    query: (sql, params) => run(pool, sql, params),
    async exec(sql) {
      await pool.query(sql);
    },
    async tx(fn) {
      for (let attempt = 0; ; attempt++) {
        const client = await pool.connect();
        try {
          await client.query('BEGIN');
          const t = { query: (sql, params) => run(client, sql, params) };
          const out = await fn(t);
          await client.query('COMMIT');
          return out;
        } catch (err) {
          await client.query('ROLLBACK').catch(() => {});
          if (RETRYABLE_PG.has(err.code) && attempt < 8) {
            await new Promise((r) => setTimeout(r, 5 + Math.random() * 20 * (attempt + 1)));
            continue;
          }
          throw err;
        } finally {
          client.release();
        }
      }
    },
    close: () => pool.end(),
  };
  await migrate(store);
  return store;
}

async function openSqlite(file) {
  const { DatabaseSync } = await import('node:sqlite');
  if (file !== ':memory:') fs.mkdirSync(path.dirname(path.resolve(file)), { recursive: true });
  const db = new DatabaseSync(file);
  db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;');
  const conv = (sql) => sql.replace(/\$(\d+)/g, '?$1');
  const cache = new Map();
  const prep = (sql) => {
    let s = cache.get(sql);
    if (!s) {
      s = db.prepare(conv(sql));
      cache.set(sql, s);
    }
    return s;
  };
  const norm = (v) => (typeof v === 'boolean' ? (v ? 1 : 0) : v === undefined ? null : v);
  const run = (sql, params = []) => {
    const st = prep(sql);
    const p = params.map(norm);
    if (/^\s*(select|with)\b/i.test(sql) || /\breturning\b/i.test(sql)) {
      const rows = st.all(...p);
      return { rows, count: rows.length };
    }
    const r = st.run(...p);
    return { rows: [], count: Number(r.changes) };
  };
  // node:sqlite is synchronous on one connection: serialise every operation
  // so a transaction's awaits never interleave with another's statements.
  let chain = Promise.resolve();
  const exclusive = (fn) => {
    const p = chain.then(fn, fn);
    chain = p.catch(() => {});
    return p;
  };
  const store = {
    kind: 'sqlite',
    forUpdate: '',
    query: (sql, params) => exclusive(() => run(sql, params)),
    exec: (sql) => exclusive(() => db.exec(sql)),
    tx: (fn) =>
      exclusive(async () => {
        db.exec('BEGIN IMMEDIATE');
        try {
          const out = await fn({ query: async (sql, params) => run(sql, params) });
          db.exec('COMMIT');
          return out;
        } catch (err) {
          db.exec('ROLLBACK');
          throw err;
        }
      }),
    async close() {
      await chain;
      db.close();
    },
  };
  await migrate(store);
  return store;
}

// ------------------------------------------------------------------ schema
// Times are ms since epoch (BIGINT). Money is an integer number of "spores".
// System ledger accounts: MINT (-1) issues currency and goes negative,
// SINK (-2) collects fees; the sum of all balances is always 0.

export const MINT = -1;
export const SINK = -2;

function schema(kind) {
  const ID = kind === 'pg' ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
  return `
CREATE TABLE IF NOT EXISTS accounts (
  id ${ID},
  name_lc TEXT NOT NULL UNIQUE,
  display TEXT NOT NULL,
  pass TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'player',
  hue REAL NOT NULL DEFAULT 0,
  totp_secret TEXT,
  totp_enabled INTEGER NOT NULL DEFAULT 0,
  recovery TEXT NOT NULL DEFAULT '[]',
  privacy_dm TEXT NOT NULL DEFAULT 'everyone',
  muted_until BIGINT NOT NULL DEFAULT 0,
  banned_until BIGINT NOT NULL DEFAULT 0,
  created BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS sessions (
  token_hash TEXT PRIMARY KEY,
  account BIGINT NOT NULL,
  created BIGINT NOT NULL,
  last_seen BIGINT NOT NULL,
  expires BIGINT NOT NULL,
  ua TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS sessions_account ON sessions(account);
CREATE TABLE IF NOT EXISTS balances (
  account BIGINT PRIMARY KEY,
  amount BIGINT NOT NULL
);
CREATE TABLE IF NOT EXISTS ledger (
  id ${ID},
  key TEXT NOT NULL UNIQUE,
  at BIGINT NOT NULL,
  kind TEXT NOT NULL,
  from_acct BIGINT NOT NULL,
  to_acct BIGINT NOT NULL,
  amount BIGINT NOT NULL,
  ref TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS ledger_from ON ledger(from_acct, at);
CREATE INDEX IF NOT EXISTS ledger_to ON ledger(to_acct, at);
CREATE TABLE IF NOT EXISTS items (
  id ${ID},
  owner BIGINT NOT NULL,
  kind TEXT NOT NULL,
  data TEXT NOT NULL,
  source_key TEXT NOT NULL UNIQUE,
  state TEXT NOT NULL DEFAULT 'held',
  lock TEXT,
  created BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS items_owner ON items(owner, state);
CREATE TABLE IF NOT EXISTS item_log (
  id ${ID},
  item BIGINT NOT NULL,
  at BIGINT NOT NULL,
  action TEXT NOT NULL,
  from_acct BIGINT,
  to_acct BIGINT,
  ref TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS item_log_item ON item_log(item);
CREATE TABLE IF NOT EXISTS listings (
  id ${ID},
  seller BIGINT NOT NULL,
  item BIGINT NOT NULL,
  price BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  buyer BIGINT,
  created BIGINT NOT NULL,
  closed BIGINT
);
CREATE INDEX IF NOT EXISTS listings_open ON listings(status, created);
CREATE TABLE IF NOT EXISTS trades (
  id ${ID},
  a BIGINT NOT NULL,
  b BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  version INTEGER NOT NULL DEFAULT 0,
  a_items TEXT NOT NULL DEFAULT '[]',
  b_items TEXT NOT NULL DEFAULT '[]',
  a_coins BIGINT NOT NULL DEFAULT 0,
  b_coins BIGINT NOT NULL DEFAULT 0,
  a_ok INTEGER NOT NULL DEFAULT 0,
  b_ok INTEGER NOT NULL DEFAULT 0,
  created BIGINT NOT NULL,
  updated BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS trades_a ON trades(a, status);
CREATE INDEX IF NOT EXISTS trades_b ON trades(b, status);
CREATE TABLE IF NOT EXISTS friends (
  a BIGINT NOT NULL,
  b BIGINT NOT NULL,
  status TEXT NOT NULL,
  requester BIGINT NOT NULL,
  created BIGINT NOT NULL,
  PRIMARY KEY (a, b)
);
CREATE INDEX IF NOT EXISTS friends_b ON friends(b);
CREATE TABLE IF NOT EXISTS blocks (
  account BIGINT NOT NULL,
  target BIGINT NOT NULL,
  created BIGINT NOT NULL,
  PRIMARY KEY (account, target)
);
CREATE TABLE IF NOT EXISTS messages (
  id ${ID},
  from_acct BIGINT NOT NULL,
  to_acct BIGINT NOT NULL,
  text TEXT NOT NULL,
  at BIGINT NOT NULL,
  read INTEGER NOT NULL DEFAULT 0,
  flagged TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS messages_to ON messages(to_acct, read);
CREATE INDEX IF NOT EXISTS messages_pair ON messages(from_acct, to_acct, at);
CREATE TABLE IF NOT EXISTS reports (
  id ${ID},
  reporter BIGINT NOT NULL,
  target BIGINT NOT NULL,
  reason TEXT NOT NULL,
  context TEXT NOT NULL DEFAULT '[]',
  at BIGINT NOT NULL,
  status TEXT NOT NULL DEFAULT 'open',
  handled_by BIGINT,
  note TEXT NOT NULL DEFAULT ''
);
CREATE INDEX IF NOT EXISTS reports_status ON reports(status, at);
CREATE TABLE IF NOT EXISTS audit (
  id ${ID},
  actor BIGINT NOT NULL,
  action TEXT NOT NULL,
  target TEXT NOT NULL DEFAULT '',
  detail TEXT NOT NULL DEFAULT '',
  at BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS audit_at ON audit(at);
`;
}

async function migrate(store) {
  const sql = schema(store.kind);
  if (store.kind === 'pg') {
    // Concurrent replicas booting at once: serialise DDL with an advisory lock.
    await store.tx(async (t) => {
      await t.query('SELECT pg_advisory_xact_lock(424242)');
      for (const stmt of sql.split(';').map((s) => s.trim()).filter(Boolean)) await t.query(stmt);
    });
  } else {
    await store.exec(sql);
  }
}
